

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
  labels:
    app: app
    role: backend
    release: "80"
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
      role: backend
  template:
    metadata:
      labels:
        app: app
        role: backend
        release: "80"
    spec:
      containers:
      - name: alpine:latest
        image: companyacr.acr.io/alpine:latest
        ports:
        - name: port-name
          containerPort: 80
        env:
        - name: MY_VARIABLE
          value: "5"
        - name: MY_VARIABLE2
          value: "123"
        livenessProbe:
            httpGet: 
                path: /api/healthy
                port: 3000
            initialDelaySeconds: 2 
            periodSeconds: 2 
            timeoutSeconds: 1 
            successThreshold: 1  
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 3000
          initialDelaySeconds: 2 
          periodSeconds: 2 
          timeoutSeconds: 1 
          successThreshold: 1  
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"